config/routes.rb
Rails.application.routes.draw do
  resources :orders
  resources :line_items
  resources :carts, path: :mon_panier
  devise_for :users
  resources :items, path: :chatons
  resources :charges
  root to: 'home#index'
  get '/a-propos-de-nous', to: 'home#about', :as => :about
  get '/contact', to: 'home#contact'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/cart.rb
class Cart < ApplicationRecord
  has_many :line_items, dependent: :destroy

  def add_item(item)
    photo = line_items.find_by(item: item)
    if photo
      photo.quantity += 1
    else
      photo = line_items.new(item: item)
    end
    photo
  end

  def total
    line_items.to_a.sum(&:total)
  end

end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  rescue_from ActiveRecord::RecordNotFound, with: :cart_not_found
  before_action :set_cart, only: [:show, :edit, :update, :destroy]

  # GET /carts
  # GET /carts.json
  def index
    @carts = Cart.all
  end

  # GET /carts/1
  # GET /carts/1.json
  def show
    if @cart.id == session[:cart_id]
    else redirect_to root_path, notice: 'Vous ne pouvez pas avoir accès aux paniers des autres utilisateurs.'
    end
  end

  # GET /carts/new
  def new
    @cart = Cart.new
  end

  # GET /carts/1/edit
  def edit
  end

  # POST /carts
  # POST /carts.json
  def create
    @cart = Cart.new(cart_params)

    respond_to do |format|
      if @cart.save
        format.html { redirect_to @cart, notice: 'Votre panier a bien été crée.' }
        format.json { render :show, status: :created, location: @cart }
      else
        format.html { render :new }
        format.json { render json: @cart.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /carts/1
  # PATCH/PUT /carts/1.json
  def update
    respond_to do |format|
      if @cart.update(cart_params)
        format.html { redirect_to @cart, notice: 'Votre panier a été mis à jour.' }
        format.json { render :show, status: :ok, location: @cart }
      else
        format.html { render :edit }
        format.json { render json: @cart.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /carts/1
  # DELETE /carts/1.json
  def destroy
    return unless @cart.id == session[:cart_id]

    @cart.destroy
    session.delete(:cart_id)

    respond_to do |format|
      format.html { redirect_to root_path, notice: ('Le panier a bien été vidé') }
      format.json { head :no_content }
    end
  end

  private

  def cart_not_found
    redirect_to root_url, alert: t("Le panier n'existe pas")
  end
    # Use callbacks to share common setup or constraints between actions.
    def set_cart
      puts "set_cart"
      @cart = Cart.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def cart_params
      params.fetch(:cart, {})
    end
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/views/carts/_form.html.erb
<%= form_with(model: cart, local: true) do |form| %>
  <% if cart.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(cart.errors.count, "error") %> prohibited this cart from being saved:</h2>

      <ul>
      <% cart.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/carts/edit.html.erb
<h1>Editing Cart</h1>

<%= render 'form', cart: @cart %>

<%= link_to 'Show', @cart %> |
<%= link_to 'Back', carts_path %>

app/views/carts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Carts</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @carts.each do |cart| %>
      <tr>
        <td><%= link_to 'Show', cart %></td>
        <td><%= link_to 'Edit', edit_cart_path(cart) %></td>
        <td><%= link_to 'Destroy', cart, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Cart', new_cart_path %>

app/views/carts/new.html.erb
<h1>New Cart</h1>

<%= render 'form', cart: @cart %>

<%= link_to 'Back', carts_path %>

app/views/carts/show.html.erb
<!-- header-banner -->
<div id="header-banner">
    <div class="banner-content single-page text-center">
        <div class="banner-border">
            <div class="banner-info">
                <h1>Panier</h1>
            </div><!-- / banner-info -->
        </div><!-- / banner-border -->
    </div><!-- / banner-content -->

</div>
<!-- / header-banner -->
</header>
<!-- / header -->

<!-- content -->

<!-- shopping-cart -->
<div id="shopping-cart">
<div class="container">
    <!-- shopping cart table -->
    <table class="shopping-cart">
        <thead>
            <tr>
                <th class="image">&nbsp;</th>
                <th>Produit</th>
                <th>Prix</th>
                <th>Quantité</th>
                <th>Total</th>
                <th>&nbsp;</th>

            </tr>
        </thead>
        <tbody>
          <% @cart.line_items.each do  |item| %>
            <tr class="cart-item">

                <td class="image"><a href="#"><img src="<%= item.item.image_url %>" alt=""></a></td>
                <td><%= link_to item_path(item.item.id) do %>
                  <%= item.item.title %>
                  <% end %>
                </td>
                <td><%= item.item.price %> €</td>
                <%= form_for(item, url: {controller: :line_items, action: :update, id: item.id}, method: :patch) do |f| %>
                <td class="qty"><%= f.number_field :quantity, id: "input-slider-value", class: "range-slider-value"%></td>
                <td><%=number_to_currency(item.item.price * item.quantity, unit: "€", separator: ",", format: "%n %u") %></td>
                <td class="text-center"><%= f.submit "Update", class: "btn btn-success-filled btn-rounded" do %><i class="fa fa-refresh"></i><% end %>
                <% end %>
                <%= link_to line_item_path(item.id), method: :delete, class: "btn btn-danger-filled btn-rounded" do %>Supprimer<% end %></td>

            </tr>
            <% end %>
        </tbody>
    </table>
    <!-- / shopping cart table -->

    <div class="row cart-footer">
        <div class="coupon col-sm-6">

        </div><!-- / input-group -->
        <div class="update-cart col-sm-6">
            <%= link_to @cart, method: :delete, data: {confirm: "Etes-vous sûr ?"}, class:"btn btn-primary-filled btn-rounded" do %>
            <i class="fa fa-cart-arrow-down"></i><span>Vider le panier</span>
            <% end %>
        </div><!-- / update-cart -->

        <div class="col-sm-6 cart-total">
            <h4>TOTAL DU PANIER</h4>
            <p>Sous-total : <span><%= @cart.total %> €</span></p>
            <p>Frais de livraison : <span>Gratuit</span></p>
            <p>Total: <span><%= @cart.total %> €</span></p>
        </div>
        <!-- / cart-total -->

        <div class="col-sm-6 cart-checkout">
            <%= link_to items_path, class: "btn btn-default-filled btn-rounded" do %>
            <i class="fa fa-shopping-cart"></i><span>Retour à la boutique</span>
            <% end %>
            <%= link_to new_order_path, method: :get, class: "btn btn-primary-filled btn-rounded" do %>
            <i class="fa fa-refresh"></i><span>Finaliser ma commande</span>
            <% end %>

        </div><!-- / cart-checkout -->


    </div><!-- / row -->
</div><!-- / container -->
</div>
<!-- / shopping-cart -->

<!-- / content -->