config/routes.rb
Rails.application.routes.draw do
  resources :orders
  resources :line_items
  resources :carts, path: :mon_panier
  devise_for :users
  resources :items, path: :chatons
  resources :charges
  root to: 'home#index'
  get '/a-propos-de-nous', to: 'home#about', :as => :about
  get '/contact', to: 'home#contact'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/_footer.html.erb
<!-- brands carousel -->
<section id="brands" class="dark primary-background">
    <h2 class="hidden">&nbsp;</h2>
    <div class="container">
        <div id="brands-carousel" class="owl-carousel">
            <div class="item"><%= image_tag "brand1.jpg" %></div>
            <div class="item"><%= image_tag "brand2.jpg" %></div>
            <div class="item"><%= image_tag "brand3.jpg" %></div>
            <div class="item"><%= image_tag "brand4.jpg" %></div>
            <div class="item"><%= image_tag "brand5.jpg" %></div>
            <div class="item"><%= image_tag "brand6.jpg" %></div>
            <div class="item"><%= image_tag "brand7.jpg" %></div>
            <div class="item"><%= image_tag "brand8.jpg" %></div>
            <div class="item"><%= image_tag "brand9.jpg" %></div>
            <div class="item"><%= image_tag "brand10.jpg" %></div>
        </div>
    </div><!-- / container -->
</section>

<!-- scroll to top -->
<a href="#top" class="scroll-to-top page-scroll is-hidden" data-nav-status="toggle"><i class="fa fa-angle-up"></i></a>
<!-- / scroll to top -->

<!-- footer -->
<footer class="light-footer">
<div class="widget-area">
    <div class="container">
        <div class="row">

            <div class="col-md-4 widget">
                <div class="about-widget">
                    <div class="widget-title-image">
                        <%= image_tag "logo.png" %>
                    </div>
                    <p>Il suffit de croiser son regard avec celui d’un chat pour mesurer la profondeur des énigmes que chaque paillette de ses yeux pose aux braves humains que nous sommes. - Jacques Laurent</p>
                </div><!-- / about-widget -->
            </div><!-- / widget -->



            <div class="col-md-2"></div>
            <!-- / third widget -->

            <div class="col-md-4 widget">
                <div class="widget-title">
                    <h4>CONTACT</h4>
                </div>
                <div class="contact-widget">
                    <div class="info">
                        <p><i class="fa fa-map-marker"></i><span>Lille</span></p>
                    </div>
                    <div class="info">
                        <a href="tel:+0123456789"><i class="fa fa-phone"></i><span>+33 606060606</span></a>
                    </div>
                    <div class="info">
                        <a href="mailto:hello@yoursite.com"><i class="fa fa-envelope-o"></i><span>thehackingproject.lille@gmail.com</span></a>
                    </div>
                    <div class="info">
                        <i class="fa fa-thumbs-o-up"></i>
                        <span class="social text-left">
                            <a class="no-margin" href="#"><i class="fa fa-facebook"></i></a>
                            <a href="#"><i class="fa fa-twitter"></i></a>
                            <a href="#"><i class="fa fa-google-plus"></i></a>
                            <a href="#"><i class="fa fa-linkedin"></i></a>
                            <a href="#"><i class="fa fa-pinterest"></i></a>
                        </span>
                    </div>
                </div><!-- / contact-widget -->
            </div><!-- / widget -->
            <!-- / fourth widget -->

        </div><!-- / row -->
    </div><!-- / container -->
</div><!-- / widget-area -->
<div class="footer-info">
    <div class="container">
            <div class="pull-left copyright">
                <p><strong>© THP LILLE #WELSH</strong></p>
            </div>
            <span class="pull-right">
              <%= image_tag "visa.png" %>
              <%= image_tag "mastercard.png" %>
              <%= image_tag "discover.png" %>
              <%= image_tag "paypal.png" %>
            </span>
    </div><!-- / container -->
</div><!-- / footer-info -->
</footer>
<!-- / footer -->

<script>
    $(document).ready(function() {
      $("#brands-carousel").owlCarousel({
        autoPlay: 5000, //set autoPlay to 5 seconds.
        items : 5,
        itemsDesktop : [1199,3],
        itemsDesktopSmall : [979,3]
      });

    });
</script>

<script>
$(document).ready(function(){
    $('[data-toggle="tooltip"]').tooltip();
});
</script>

app/views/layouts/_navbar.html.erb
<div id="top"></div>
<!-- nav -->
<nav class="navbar navbar-default nav-sec navbar-fixed-top">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            </button>
            <%= link_to root_path do %>
            <div class="navbar-brand"><%= image_tag "logo.png"%></div>
            <%end%>
        </div><!-- / navbar-header -->
        <div class="secondary-nav">
          <% if current_user %>
            <% if current_user.admin? %>
            <a>
            <span class="text-danger">Mode Admin&nbsp;&nbsp;&nbsp;</span></a>
            <% end %>
          <% end %>
          <a href="#" class="dropdown-toggle my-account space-right fa fa-user" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"></a>
          <ul class="dropdown-menu animated zoomIn fast">

            <% if user_signed_in? %>
              <li><%= link_to edit_user_registration_path(@user) do %>
                <span>Voir/Editer mon profil</span>
                <% end %>
              </li>
              <li><%= link_to destroy_user_session_path, method: :delete do %>
                <span>Se déconnecter</span>
                <% end %>
              </li>
            <% else %>
              <li><%= link_to new_user_session_path do %>
                <span>Se connecter</span>
                <% end %>
            <% end %>
          </ul>
          <% if @cart %>
            <%= link_to @cart, class: "shopping-cart" do %>
              <i class="fa fa-shopping-cart"></i> <span class="cart-badge"><%= @cart.line_items.count %></span>
            <% end %>
          <% else %>
            <%= link_to @cart, class: "shopping-cart" do %>
              <i class="fa fa-shopping-cart"></i> <span class="cart-badge">0</span>
            <% end %>
          <% end %>
        </div>
        <div class="navbar-collapse collapse text-center">
            <ul class="nav navbar-nav">
              <li class="active"><%= link_to root_path do %>
                <span>HOME</span><%end%></li>
              <li><%= link_to items_path do %>
                <span>BOUTIQUE</span><%end%></li>
              <li><%= link_to about_path do %>
                <span>A PROPOS DE NOUS</span><%end%></li>
              <li><%= link_to contact_path do %>
                <span>CONTACT</span><%end%></li>
            </ul>
        </div><!--/ nav-collapse -->
    </div><!-- / container -->
</nav>
<!-- / nav -->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Matouri</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="https://fonts.googleapis.com/css?family=Rubik:400,500,700,900" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Lily+Script+One" rel="stylesheet">
  </head>

  <body>
    <%= render 'layouts/navbar' %>
    <p  class="alert"><%= alert %></p>
    <p  class="notice" ><%= notice %></p>
    <p  id="alert"><%= alert %></p>
    <p  id="notice" ><%= notice %></p>
    <%= yield %>
    <%= render 'layouts/footer' %>
  </body>
</html>